In [4]:
import numpy as np

- create
- basic operation
- math operation
- indexing and slicing
- boolean filter

In [9]:
x = np.array([1,2,3,4,5])
print(x)
print(x.shape)

[1 2 3 4 5]
(5,)


In [8]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [10]:
b = np.array([[1,2,3],[4,5,6],[7,9,9]])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]
 [7 9 9]]
(3, 3)


In [11]:
z = [0,1,2,3,4,5,6,7,8,9]
nz = np.array([z]*10)
print(nz)
print(nz.shape)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
(10, 10)


- random
- arange
- linspace

In [12]:
np.random.rand(3,3)

array([[0.15665572, 0.62310698, 0.48422216],
       [0.47600464, 0.4443757 , 0.20679805],
       [0.09670811, 0.82824904, 0.99431137]])

In [14]:
r1 = np.random.randint(-5,6, (5,5))
print(r1)

[[ 5  2 -2  5  3]
 [ 5  2 -4 -3  5]
 [-5  5 -4  5  4]
 [-2 -2 -2 -4 -5]
 [-2  2  5  2  5]]


In [17]:
# start, stop, gap
np.arange(0,50, .5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. ,
       27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5,
       33. , 33.5, 34. , 34.5, 35. , 35.5, 36. , 36.5, 37. , 37.5, 38. ,
       38.5, 39. , 39.5, 40. , 40.5, 41. , 41.5, 42. , 42.5, 43. , 43.5,
       44. , 44.5, 45. , 45.5, 46. , 46.5, 47. , 47.5, 48. , 48.5, 49. ,
       49.5])

In [19]:
# start, stop, number_of_items
np.linspace(0,50, 100)

array([ 0.        ,  0.50505051,  1.01010101,  1.51515152,  2.02020202,
        2.52525253,  3.03030303,  3.53535354,  4.04040404,  4.54545455,
        5.05050505,  5.55555556,  6.06060606,  6.56565657,  7.07070707,
        7.57575758,  8.08080808,  8.58585859,  9.09090909,  9.5959596 ,
       10.1010101 , 10.60606061, 11.11111111, 11.61616162, 12.12121212,
       12.62626263, 13.13131313, 13.63636364, 14.14141414, 14.64646465,
       15.15151515, 15.65656566, 16.16161616, 16.66666667, 17.17171717,
       17.67676768, 18.18181818, 18.68686869, 19.19191919, 19.6969697 ,
       20.2020202 , 20.70707071, 21.21212121, 21.71717172, 22.22222222,
       22.72727273, 23.23232323, 23.73737374, 24.24242424, 24.74747475,
       25.25252525, 25.75757576, 26.26262626, 26.76767677, 27.27272727,
       27.77777778, 28.28282828, 28.78787879, 29.29292929, 29.7979798 ,
       30.3030303 , 30.80808081, 31.31313131, 31.81818182, 32.32323232,
       32.82828283, 33.33333333, 33.83838384, 34.34343434, 34.84

array attributes
- shape
- dtype
- ndim
- size

basic operations
- sum
- mean
- min
- max
- std
- reshape
- transpose
- flatten

In [20]:
x.dtype

dtype('int64')

In [21]:
x = np.random.rand(3,3)
x.dtype

dtype('float64')

In [22]:
x.ndim

2

In [23]:
z = np.random.randint(1,5, (3,3,3))
z.ndim

3

In [26]:
z.size    # total element in the array 

27

In [27]:
z.sum()

np.int64(58)

In [31]:
a = np.random.rand(2,3)
print(a.sum())
print(a.sum(axis=0))   # column-wise
print(a.sum(axis=1))   # row-wise

print(a.mean())
print(a.max())
print(a.min())
print(a.std())
print(a.var())
# all the methods can be used with axis

3.8318402011300496
[1.36101855 1.29371556 1.17710609]
[2.61262449 1.21921571]
0.638640033521675
0.9726989525173804
0.3634599278878504
0.23983542882624292
0.057521032920267834


In [33]:
z = np.random.randint(11,99, (5,5))
print(z)
print('transpose')
print(z.transpose())   # or print(z.T)
print('flattened')
print(z.flatten())

[[48 72 74 57 79]
 [49 31 22 87 62]
 [75 15 25 82 74]
 [53 56 95 88 40]
 [11 18 69 78 94]]
transpose
[[48 49 75 53 11]
 [72 31 15 56 18]
 [74 22 25 95 69]
 [57 87 82 88 78]
 [79 62 74 40 94]]
flattened
[48 72 74 57 79 49 31 22 87 62 75 15 25 82 74 53 56 95 88 40 11 18 69 78
 94]


In [35]:
a = np.random.randint(1,10, (4,5))
print(a)
print(a.reshape(20))
print(a.reshape(5,4))
print(a.reshape(2,10))
print(a.reshape(10,2))
# print(a.reshape(5,2,2))

[[7 6 8 1 4]
 [1 7 1 7 6]
 [1 7 7 5 2]
 [2 4 3 2 3]]
[7 6 8 1 4 1 7 1 7 6 1 7 7 5 2 2 4 3 2 3]
[[7 6 8 1]
 [4 1 7 1]
 [7 6 1 7]
 [7 5 2 2]
 [4 3 2 3]]
[[7 6 8 1 4 1 7 1 7 6]
 [1 7 7 5 2 2 4 3 2 3]]
[[7 6]
 [8 1]
 [4 1]
 [7 1]
 [7 6]
 [1 7]
 [7 5]
 [2 2]
 [4 3]
 [2 3]]


In [36]:
a = np.array([[1,2],[3,4]])
b = np.array([[6,2],[6,3]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[6 2]
 [6 3]]


In [37]:
# when using 2 matrix, the shape must be the same
print(a + b)
print(a - b)
print(a / b)   # element-wise divison
print(a * b)   # element-wise multiplication
print(a @ b)   # matrix multiplication
print(a.dot(b))   # matrix multiplication

[[7 4]
 [9 7]]
[[-5  0]
 [-3  1]]
[[0.16666667 1.        ]
 [0.5        1.33333333]]
[[ 6  4]
 [18 12]]
[[18  8]
 [42 18]]
[[18  8]
 [42 18]]


In [38]:
# when using matrix and scalar
print(a - 10)   # broadcasting
print(a * 10)   # broadcasting
print(a / 10)   # broadcasting
print(a + 10)   # broadcasting

[[-9 -8]
 [-7 -6]]
[[10 20]
 [30 40]]
[[0.1 0.2]
 [0.3 0.4]]
[[11 12]
 [13 14]]


In [40]:
# indexing
print(a[0,0])
print(a[-1,-1])

1
4


syntax of slicing
- arr[rowstart:rowstop:rowgap,columnstart:columnstop:columngap]

In [42]:
# slicing
x = np.random.randint(1,10, (5,5))
print(x)
print(x[:,0])  # first column
print(x[:,-1])  # last column
print(x[:,:3])  # first 3 columns

[[7 9 7 5 7]
 [7 2 6 6 1]
 [3 3 3 1 9]
 [1 7 3 4 1]
 [4 7 6 7 5]]
[7 7 3 1 4]
[7 1 9 1 5]
[[7 9 7]
 [7 2 6]
 [3 3 3]
 [1 7 3]
 [4 7 6]]


In [43]:
print([x[1:4,1:4]])

[array([[2, 6, 6],
       [3, 3, 1],
       [7, 3, 4]], dtype=int32)]
